import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";

import { api } from "../utils/api";
import { useRouter } from "next/router";
import AcuteDashboard from "../components/AcuteDashboard";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const router = useRouter()
  const { status, data: session } = useSession({
    required: true,
    onUnauthenticated() {
      router.push("/auth/signin")
    }
  })

  if (status === "loading") {
    return <div>Loading...</div>
  }

  return (
    <>
      <Head>
        <title>PLR</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AcuteDashboard />
    </>
  );
};

export default Home;
